version: "3.8"

services:
  app-test:
    build:
      context: ..
      dockerfile: docker/Dockerfile.test
    container_name: ai-planner-api-test
    environment:
      - NODE_ENV=test
      - PORT=5001
      - REDIS_HOST=redis-test
      - REDIS_PORT=6379
      - FIREBASE_PROJECT_ID=test-project
      - JWT_SECRET=test-jwt-secret
      - TEST_DATABASE_URL=mongodb://mongo-test:27017/ai-planner-test
    ports:
      - "5001:5001"
    volumes:
      - ../tests:/app/tests:ro
    depends_on:
      - redis-test
      - mongo-test
    networks:
      - ai-planner-test-network
    command: ["npm", "run", "test:integration"]

  redis-test:
    image: redis:7-alpine
    container_name: ai-planner-redis-test
    ports:
      - "6380:6379"
    networks:
      - ai-planner-test-network

  mongo-test:
    image: mongo:6-jammy
    container_name: ai-planner-mongo-test
    ports:
      - "27018:27017"
    environment:
      - MONGO_INITDB_DATABASE=ai-planner-test
    networks:
      - ai-planner-test-network

  test-runner:
    build:
      context: ..
      dockerfile: docker/Dockerfile.test
    container_name: ai-planner-test-runner
    environment:
      - NODE_ENV=test
      - CI=true
    volumes:
      - ..:/app:ro
    depends_on:
      - app-test
    networks:
      - ai-planner-test-network
    profiles:
      - test
    command: ["npm", "run", "test:coverage"]

networks:
  ai-planner-test-network:
    driver: bridge
